/**
 * Persian → Finglish for email local-part.
 * Order: full-name dict → word tokens → digraphs → chars.
 * All dict keys are quoted (spaces / ZWNJ are not valid bare identifiers).
 */

const NAME_DICT: Record<string, string> = {
  علی: "ali",
  علیرضا: "alireza",
  "علی‌رضا": "alireza",
  محمد: "mohammad",
  محمدعلی: "mohammadali",
  محمدحسین: "mohammadhossein",
  محمدرضا: "mohammadreza",
  مهدی: "mahdi",
  مهدي: "mahdi",
  حسین: "hossein",
  حسن: "hasan",
  رضا: "reza",
  امیر: "amir",
  امیرحسین: "amirhossein",
  امیرمحمد: "amirmohammad",
  سعید: "saeed",
  سعيد: "saeed",
  مجید: "majid",
  مجيد: "majid",
  حمید: "hamid",
  حميد: "hamid",
  حمیدرضا: "hamidreza",
  جواد: "javad",
  احمد: "ahmad",
  محمود: "mahmoud",
  عباس: "abbas",
  اکبر: "akbar",
  اصغر: "asghar",
  یاسر: "yaser",
  یاسین: "yasin",
  یوسف: "yousef",
  يوسف: "yousef",
  ابراهیم: "ebrahim",
  اسماعیل: "esmaeil",
  اسماعيل: "esmaeil",
  مصطفی: "mostafa",
  مصطفي: "mostafa",
  مرتضی: "morteza",
  مرتضي: "morteza",
  کاظم: "kazem",
  كاظم: "kazem",
  ناصر: "naser",
  نادر: "nader",
  فرهاد: "farhad",
  فرید: "farid",
  فريد: "farid",
  فرزاد: "farzad",
  فرشاد: "farshad",
  فرشید: "farshid",
  بهرام: "bahram",
  بهروز: "behrouz",
  بهنام: "behnam",
  بهمن: "bahman",
  بابک: "babak",
  پرویز: "parviz",
  پرويز: "parviz",
  پیمان: "peyman",
  پویا: "pouya",
  پوريا: "pouria",
  پوریا: "pouria",
  کیان: "kian",
  کیوان: "keyvan",
  کوروش: "kourosh",
  آرش: "arash",
  آرمان: "arman",
  آرمین: "armin",
  آریا: "arya",
  سینا: "sina",
  سينا: "sina",
  سامان: "saman",
  سام: "sam",
  سهراب: "sohrab",
  شهاب: "shahab",
  شهرام: "shahram",
  شاهین: "shahin",
  داریوش: "dariush",
  داوود: "davoud",
  داود: "davoud",
  عبدالله: "abdollah",
  عبداله: "abdollah",
  محسن: "mohsen",
  مهدیار: "mahdiyar",
  میلاد: "milad",
  میلان: "milan",
  ایمان: "iman",
  ايمان: "iman",
  احسان: "ehsan",
  اشکان: "ashkan",
  افشین: "afshin",
  امید: "omid",
  اميد: "omid",
  انوشیروان: "anoushirvan",
  بیژن: "bijan",
  جلال: "jalal",
  جمال: "jamal",
  جهانگیر: "jahangir",
  حافظ: "hafez",
  حبیب: "habib",
  خشایار: "khashayar",
  رامین: "ramin",
  رامين: "ramin",
  رسول: "rasoul",
  سروش: "soroush",
  صمد: "samad",
  صادق: "sadegh",
  طاهر: "taher",
  عادل: "adel",
  عارف: "aref",
  عرفان: "erfan",
  "علی‌اکبر": "aliakbar",
  "علی اکبر": "aliakbar",
  قاسم: "ghasem",
  کامبیز: "kambiz",
  کامران: "kamran",
  کسری: "kasra",
  مازیار: "maziar",
  مانی: "mani",
  مهران: "mehran",
  مهرداد: "mehrdad",
  نوید: "navid",
  نويد: "navid",
  نیما: "nima",
  نيما: "nima",
  وحید: "vahid",
  وحيد: "vahid",
  هادی: "hadi",
  هادي: "hadi",
  هومن: "houman",
  همایون: "homayoun",
  یحیی: "yahya",
  فاطمه: "fatemeh",
  "فاطمه زهرا": "fatemehzahra",
  زهرا: "zahra",
  مریم: "maryam",
  زینب: "zeynab",
  زينب: "zeynab",
  سارا: "sara",
  نرگس: "narges",
  نازنین: "nazanin",
  نسيم: "nasim",
  نسیم: "nasim",
  نیلوفر: "niloufar",
  نيلوفر: "niloufar",
  مینا: "mina",
  مهسا: "mahsa",
  مهناز: "mahnaz",
  مونا: "mona",
  هانیه: "hanieh",
  هانيه: "hanieh",
  هستی: "hasti",
  هلیا: "helia",
  الهام: "elham",
  الهه: "elahe",
  آیدا: "aida",
  ایدا: "aida",
  آتنا: "atena",
  آتوسا: "atousa",
  پریسا: "parisa",
  پریا: "pariya",
  پگاه: "pegah",
  شیرین: "shirin",
  شيرين: "shirin",
  شیدا: "sheida",
  سمیرا: "samira",
  سميرا: "samira",
  سمیه: "somayeh",
  سعیده: "saeedeh",
  لیلا: "leila",
  ليلا: "leila",
  لیدا: "lida",
  رویا: "roya",
  ريا: "roya",
  ریحانه: "reyhaneh",
  راضیه: "razie",
  طاهره: "tahereh",
  گلناز: "golnaz",
  گلسا: "golsa",
  کیمیا: "kimia",
  مهتاب: "mahtab",
  مهرناز: "mehrnaz",
  نگین: "negin",
  ياسمن: "yasaman",
  یاسمن: "yasaman",
  یاس: "yas",
  محمدی: "mohammadi",
  حسینی: "hosseini",
  رضایی: "rezaei",
  رضائی: "rezaei",
  احمدی: "ahmadi",
  موسوی: "mousavi",
  کریمی: "karimi",
  كريمي: "karimi",
  جعفری: "jafari",
  جعفري: "jafari",
  حیدری: "heidari",
  حيدري: "heidari",
  نوری: "nouri",
  نوري: "nouri",
  اکبری: "akbari",
  كاظمي: "kazemi",
  کاظمی: "kazemi",
  عباسی: "abbasi",
  مرادی: "moradi",
  مرادي: "moradi",
  علیزاده: "alizadeh",
  عليزاده: "alizadeh",
  محمدزاده: "mohammadzadeh",
  رحیمی: "rahimi",
  رحيمي: "rahimi",
  صالحی: "salehi",
  طاهری: "taheri",
  صادقی: "sadeghi",
  باقری: "bagheri",
  نجفی: "najafi",
  شریفی: "sharifi",
  قاسمی: "ghasemi",
  یوسفی: "yousefi",
  يوسفي: "yousefi",
  اسدی: "asadi",
  فرهادی: "farhadi",
  بهرامی: "bahrami",
  پناهی: "panahi",
  نظری: "nazari",
  امینی: "amini",
  هاشمی: "hashemi",
  میرزایی: "mirzaei",
  میرزائی: "mirzaei",
  سلطانی: "soltani",
  پارسا: "parsa",
  رستمی: "rostami",
  رستمي: "rostami",
  اخلاقی: "akhlaghi",
  اکلاقی: "akhlaghi",
  جلالی: "jalali",
  کرمی: "karami",
  كرمي: "karami",
  قربانی: "ghorbani",
  "قاسم‌زاده": "ghasemzadeh",
  نژاد: "nejad",
  پور: "pour",
  زاده: "zadeh",
};

/** Longest digraphs first */
const DIGRAPHS: Array<[string, string]> = [
  ["خوا", "kha"],
  ["خو", "kho"],
  ["خا", "kha"],
  ["خی", "khi"],
  ["چه", "che"],
  ["چی", "chi"],
  ["چا", "cha"],
  ["چو", "cho"],
  ["شه", "she"],
  ["شا", "sha"],
  ["شو", "sho"],
  ["شی", "shi"],
  ["ژه", "zhe"],
  ["ژا", "zha"],
  ["غو", "gho"],
  ["غا", "gha"],
  ["غی", "ghi"],
  ["قه", "ghe"],
  ["قا", "gha"],
  ["قو", "gho"],
  ["قی", "ghi"],
  ["له", "leh"],
  ["لا", "la"],
  ["لو", "lou"],
  ["لی", "li"],
  ["مه", "meh"],
  ["ما", "ma"],
  ["مو", "mo"],
  ["می", "mi"],
  ["نه", "neh"],
  ["نا", "na"],
  ["نو", "no"],
  ["نی", "ni"],
  ["به", "beh"],
  ["با", "ba"],
  ["بو", "bou"],
  ["بی", "bi"],
  ["ده", "deh"],
  ["دا", "da"],
  ["دو", "dou"],
  ["دی", "di"],
  ["ته", "teh"],
  ["تا", "ta"],
  ["تو", "tou"],
  ["تی", "ti"],
  ["ره", "reh"],
  ["را", "ra"],
  ["رو", "rou"],
  ["ری", "ri"],
  ["زه", "zeh"],
  ["زا", "za"],
  ["زو", "zou"],
  ["زی", "zi"],
  ["سه", "seh"],
  ["سا", "sa"],
  ["سو", "sou"],
  ["سی", "si"],
  ["فه", "feh"],
  ["فا", "fa"],
  ["فو", "fou"],
  ["فی", "fi"],
  ["که", "keh"],
  ["كا", "ka"],
  ["کا", "ka"],
  ["کو", "kou"],
  ["کی", "ki"],
  ["گه", "geh"],
  ["گا", "ga"],
  ["گو", "gou"],
  ["گی", "gi"],
  ["جه", "jeh"],
  ["جا", "ja"],
  ["جو", "jou"],
  ["جی", "ji"],
  ["عه", "eh"],
  ["عا", "a"],
  ["عو", "ou"],
  ["عی", "ei"],
  ["حه", "heh"],
  ["حا", "ha"],
  ["حو", "hou"],
  ["حی", "hi"],
  ["یه", "yeh"],
  ["یا", "ya"],
  ["یو", "you"],
  ["یی", "yi"],
];

const CHARS: Record<string, string> = {
  آ: "a",
  ا: "a",
  ب: "b",
  پ: "p",
  ت: "t",
  ث: "s",
  ج: "j",
  چ: "ch",
  ح: "h",
  خ: "kh",
  د: "d",
  ذ: "z",
  ر: "r",
  ز: "z",
  ژ: "zh",
  س: "s",
  ش: "sh",
  ص: "s",
  ض: "z",
  ط: "t",
  ظ: "z",
  ع: "a",
  غ: "gh",
  ف: "f",
  ق: "gh",
  ک: "k",
  ك: "k",
  گ: "g",
  ل: "l",
  م: "m",
  ن: "n",
  و: "o",
  ه: "h",
  ی: "i",
  ي: "i",
  ئ: "i",
  ء: "",
  ة: "h",
  ؤ: "o",
  إ: "e",
  أ: "a",
  ٱ: "a",
};

function normalizeFa(text: string): string {
  return text
    .trim()
    .replace(/[\u200c\u200d\u0640]/g, "")
    .replace(/\s+/g, " ");
}

function mapToken(token: string): string {
  const key = normalizeFa(token);
  if (!key) return "";
  if (NAME_DICT[key]) return NAME_DICT[key];

  // Also try with ZWNJ restored variants already stripped by normalize
  let rest = key;
  let out = "";
  while (rest.length > 0) {
    let hit = false;
    for (const [from, to] of DIGRAPHS) {
      if (rest.startsWith(from)) {
        out += to;
        rest = rest.slice(from.length);
        hit = true;
        break;
      }
    }
    if (hit) continue;
    const ch = rest[0];
    out += CHARS[ch] ?? (/[a-zA-Z0-9]/.test(ch) ? ch.toLowerCase() : "");
    rest = rest.slice(1);
  }
  return out;
}

export function transliterateFa(text: string): string {
  const normalized = normalizeFa(text);
  if (!normalized) return "";
  if (NAME_DICT[normalized]) return NAME_DICT[normalized];

  return normalized
    .split(/\s+/)
    .filter(Boolean)
    .map(mapToken)
    .filter(Boolean)
    .join(" ");
}

export function slugNamePart(value: string): string {
  let s = transliterateFa(value).toLowerCase();
  s = s.replace(/[^a-z0-9]+/g, ".");
  s = s.replace(/\.{2,}/g, ".").replace(/^\.|\.$/g, "");
  return s;
}

export function suggestEmailLocalPart(firstName: string, lastName: string): string {
  const first = slugNamePart(firstName);
  const last = slugNamePart(lastName);
  if (!first && !last) return "";
  if (!first) return last;
  if (!last) return first;
  return `${first}.${last}`;
}
